### ISSUE TITLE
Running Target Issue

### ISSUE THREAD

**Issue by digitalsense** [sebastiangraf/jSCSI#13]
Hi,

I wanting to work with the library to create a virtual iSCSI interface for a project. I cant seem to get it to work. Everything compiles fine, it executes, asks for the IP etc.

As soon as i try to connect to it, it throws 1000's of errors (as below).

17:04:02.449 [main] ERROR o.j.t.c.Connection$TargetConnection - Exception throws
java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:1.7.0_55]
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:1.7.0_55]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.7.0_55]
        at sun.nio.ch.IOUtil.read(IOUtil.java:197) ~[na:1.7.0_55]
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379) ~[na:1.7.0_55]
        at org.jscsi.parser.ProtocolDataUnit.read(ProtocolDataUnit.java:356) ~[target-2.5.3-SNAPSHOT-jar-with-dependencies.jar:na]
        at org.jscsi.target.connection.TargetSenderWorker.receiveFromWire(TargetSenderWorker.java:133) ~[target-2.5.3-SNAPSHOT-jar-with-dependencies.jar:na]
        at org.jscsi.target.connection.Connection$TargetConnection.receivePdu(Connection.java:169) [target-2.5.3-SNAPSHOT-jar-with-dependencies.jar:na]
        at org.jscsi.target.connection.phase.TargetFullFeaturePhase.execute(TargetFullFeaturePhase.java:82) ~[target-2.5.3-SNAPSHOT-jar-with-dependencies.jar:na]
        at org.jscsi.target.connection.Connection$TargetConnection.call(Connection.java:225) [target-2.5.3-SNAPSHOT-jar-with-dependencies.jar:na]
        at org.jscsi.target.connection.Connection$TargetConnection.call(Connection.java:66) [target-2.5.3-SNAPSHOT-jar-with-dependencies.jar:na]
        at org.jscsi.target.TargetServer.call(TargetServer.java:242) [target-2.5.3-SNAPSHOT-jar-with-dependencies.jar:na]
        at org.jscsi.target.TargetServer.main(TargetServer.java:192) [target-2.5.3-SNAPSHOT-jar-with-dependencies.jar:na]

has anyone seen this before? Your help is much appreciated.

**Comment by ActiveVolcano** [comment]
Microsoft Windows 8 and Linux CentOS 6 seem outdated in this year 2022.
However, with pull request #43 and #44,
jSCSI target is now compatible with Microsoft Windows 10 and Linux CentOS 7.

> I have tried it on both Windows 8 (using Eclipse and JDK 1.7) and Centos 6.2 using OpenJDK 1.6.
> 
> Yes i am only looking to work with the Target. It builds on both platforms just fine. It launches just fine, i can see the iSCSI shares (on discovery). But i get this error on both platforms when i try to connect/use the drives.
